name: Compila Crash Windows MSYS2 Patchato

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configura MSYS2 ed installa dipendenze
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        update: true
        install: >-
          mingw-w64-i686-gcc
          mingw-w64-i686-SDL2
          mingw-w64-i686-SDL2_mixer
          mingw-w64-i686-SDL2_ttf
          make

    - name: Applica Patch al Codice Sorgente
      shell: msys2 {0}
      run: |
        sed -i 's/SwpClose(swp_access_num);/SwpClose();/g' src/midi.c

    - name: Compilazione con Make
      shell: msys2 {0}
      run: |
        make

    - name: Salva l'eseguibile Windows
      uses: actions/upload-artifact@v4
      with:
        name: crash-windows-bin
        path: |
          c1.exe
